### ISSUE TITLE
Examples are not tested

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/scikit-cosmo#68]
We intend to run examples in `examples/` in CI to ensure they stay up to date; but our setup leaves a lot to be desired. 

- We are currently trying to run jupyter notebooks using `nbconvert --execute`, but for some reason I could not understand the resulting scripts are **not** executed. The nbconvert command works fine locally, so I guess this is down to some configuration difference.

- #58 is introducing pure python script as examples, which are currently not tested at all. We would need to add them to tox setup as well.

**Comment by agoscinski** [comment]
Regarding the first point it seems that is because the bash script executing the nbconvert still exits with 0. So even when an error appears in the notebook (which is outputted in the terminal), the bash script says everything is okay, therefore tox says everything is okay. 

I am not sure how to solve this in a nice way, one could make a python script which runs a python file (from the converted notebooks) in a try except block and exits with exit(0) or exist(1).
